### ISSUE TITLE
Provide option to reject unrecognized flags

### ISSUE THREAD

**Issue by collinvandyck** [jimmycuadra/lita-keyword-arguments#3]
Would be great if there were the ability to throw an error or provide some sort of signal to the client of this code that there were some arguments that were provided but weren't supplied in the schema.

So for example if I specified that my lita plugin wanted to support `--user` and the user actually typed in `-usr`, i'd like to be able to detect that. 

Ideally this would be an option we could configure `lita-keyword-arguments` with so that it would not break existing behavior.

**Comment by benodom** [comment]
:+1:

**Comment by jimmycuadra** [comment]
I like that idea. PRs implementing this are welcome. In the meantime, I will leave this issue open as a feature request.
