### ISSUE TITLE
Detect empty argument values

### ISSUE THREAD

**Issue by eik3** [jimmycuadra/lita-keyword-arguments#4]
It would be great to be able to detect if a flag that needs an argument got called without one.
Example:
`-n` is an optional flag that needs an argument to make sense to the command. 
So it would be ok to do 
`command`
But I'd like to throw an error in these cases:
`command -n` (empty flag argument)
`command -a -n -b` (again empty, in between other flags)

Currently, in all the above cases the value of `-n` is `nil` or whatever I specify as default.

**Comment by jimmycuadra** [comment]
Throw an error as in raise an exception? You'd need to explicitly rescue it in your plugin in order to handle that case. I'm not sure that has much value beyond checking if an expected value is nil.

**Comment by eik3** [comment]
No sorry not an Ruby exception, I rather meant "reply to the user with an error message like 'Flag -n needs a value!'"

**Comment by jimmycuadra** [comment]
Ah, I see. I think that is beyond the scope of what I want this extension to do, but it should be possible to do that in an additional extension that builds on this one. You could always do it in the handler using this extension, as well.
